### ISSUE TITLE
LDAP displayName?

### ISSUE THREAD

**Issue by notaus557** [bigbluebutton/greenlight#1759]
I used the docker container release 2.5.6 together with ldap login.
Everything worked fine, I  saw the displayName (or sn + givenName ?) as  Name in Greenlight.

Switched then to 2.6.4 and now the shown Name is my sAMAccountName.
Because you cannot change it anymore, all other BBB users see this cryptic name.

Can you change this behaviour back?

(you have to delete the user profile and then login with ldap again so that the field is imported again)

**Comment by farhatahmad** [comment]
Going to try and implement LDAP attribute mapping because no matter how it's set now, nobody seems to be happy

**Comment by Tecumtha** [comment]
@notaus557 

Same Problem here... i Updated from 2.5.6 to 2.6.4 and the Usernames are not "Human readable". 

A little dirty Trick, thats works for me was:

The only Change in the Gem bn-ldap-authentication-0.1.3 was the line:
'name' => [:cn, :displayName],
on bn-ldap-authentication-0.1.2, it works with my ldap.

so i edit the file in the docker container:

/usr/src/app/vendor/bundle/ruby/2.5.0/gems/bn-ldap-authentication-0.1.3/lib/bn-ldap-authentication.rb

And replace the string 'name' => [:cn, :displayName], with the old one : 'name' => [:displayName, :cn],

After a Container-Restart it work like in 2.5.6

You can also use the older Gemfile, but this was my first Idea and it  works for me. so.... :)

**Comment by mk-hs** [comment]
Thank you! The new ldap mapping works perfectly.

**Comment by farhatahmad** [comment]
Should be fixed in 2.6.5. See the `LDAP_ATTRIBUTE_MAPPING` section here: https://docs.bigbluebutton.org/greenlight/gl-config.html#ldap-auth

**Comment by jolly-jump** [comment]
Hi, may I comment on this?
I have used Greenlight now since probably 2.6.5 maybe even before that.
I have not used any LDAP_ATTRIBUTE_MAPPING so far and all the "Displaynames" have only the uid/samAccountName, which I am unhappy of.

Now I found out about the LDAP_Attribute_mapping using 2.7.16 and figured it does still not work.

I tried deleting my own account then logging in again, still the display name is the uid.

Is the LDAP_ATTRIBUTE_MAPPING=name=displayName; broken or am I missing something?
