### ISSUE TITLE
[v3] Locale not remembered after sign out

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/greenlight#4450]
**Describe the bug**
Once you sign out GLv3, the locale setting is not kept.

**To Reproduce**
1. Sign in GLv3
2. Change locale from the profile setting
3. You sign out
4. The sign-in/sign-up page turns English. If you sign-in, the locale gets back to English

**Expected behavior**
The user's locale setting should be remembered after signing out.

**Actual behavior**
Not remembered, gets back to English.

**Screenshots**

**Additional context**

**Comment by hiroshisuga** [comment]
No it's Japanese.

**Comment by farhatahmad** [comment]
Hmm this is odd. Here's what's supposed to happen.

1- If not signed in, you should see the language of your browser (english if your language isn't supported)
2- If you sign up, you should be assigned the language of your browser as your language
3- Signing in should show the language that you are assigned

Are you using the latest beta9 release?

**Comment by hiroshisuga** [comment]
That's strange, actually..
Yes, I am using beta9.
On the demo.bigbluebutton.org server, I get the error "Oops! Something went wrong. If the incident occurs again, please contact the administrator" when I change the locale (but actually the locale changed when reload the page). However, once sign-out and sign-in again, the changed locale won't be remembered (back to English). I tested changing to Japanese and German, both ended up with the same problem.

**Comment by farhatahmad** [comment]
Hmm - I was able to replicate that on demo - let me take a look to see why that might happen

**Comment by farhatahmad** [comment]
Should be fixed in the latest version. Please try again on demo

**Comment by hiroshisuga** [comment]
No error anymore, but the locale is not remembered after signing out.
Browser: Brave (English)
OS: Windows 10 64 bit (English)
![Animation1](https://user-images.githubusercontent.com/45039819/214204118-351f5841-e7f2-4357-89b8-4ee13f7bc822.gif)

**Comment by farhatahmad** [comment]
Made the change on my local machine and forgot to push it :man_facepalming:. Will get it as part of the next release

**Comment by hiroshisuga** [comment]
@farhatahmad, I confirmed that the locale remembered even after signing out. Thanks!

However, the welcome page (when not signing in) still does not seem to respect the browser's locale setting, neither the account locale setting of Windows. More precisely, the Japanese page appears just for an instance then it immediately turns into English. I tested Brave, Chrome, Firefox (locale Japanese) on Windows10 (locale Japanese as well).
I remember (need to confirm) that on Android the welcome page was shown in Japanese on Brave browser.

**Comment by hiroshisuga** [comment]
@farhatahmad , I have confirmed that the GLv3 respects German locale setting on my Chrome browser (I got the Willkommen message ;-) 
So it's likely a problem in Japanese locale. One possibility is that the Japanese locale in GL is set for ja_JP, but not ja. Is it possible that we need a conversion from ja to ja_JP somewhere in the code?

**Comment by farhatahmad** [comment]
Yeah that's likely it. The way locales work is if you request 'ja_JP', it serves both 'ja_JP' and 'ja'. If you request 'ja' it serves only 'ja'

**Comment by hiroshisuga** [comment]
#4699 solved the problem for Japanese.
