### ISSUE TITLE
extra forward slash in API call

### ISSUE THREAD

**Issue by slate17** [bigbluebutton/greenlight#4924]
Hi,

I've just installed a Standalone Instance of Greenlight v3.

No matter how i enter the BIGBLUEBUTTON_ENDPOINT in the .env-file (with or without trailing slash / with or without /api at the end)
Greenlight is always adding an extra forward slashes after the Endpoint.

like this:
`https://app.bbbserver.de/de/bbb-integration/bigbluebutton/api//create?guestPolicy=ALWAYS_ACCEPT(...)`

when I copy the URL, remove the extra slash and then make the call, it is successful.

Is it a bug or am I doing something wrong?
Hope someone can help me.

-slate

**Comment by slate17** [comment]
Yes, 3.0.1
I used gl-install.sh

I did docker-compose down and docker-compose up after every change. I did try various formats including the one you have suggested. 
 Weird. 

-slate

**Comment by farhatahmad** [comment]
Ah wait, I sese that now `https://dev26.bigbluebutton.org/bigbluebutton/api//create?guestPolicy=ASK_MODERATOR&...`

I'll take a look into this

**Comment by farhatahmad** [comment]
This seems to have been a problem for a while now, but the request should still go through. Is yours failing? 

I've fixed it here: https://github.com/mconf/bigbluebutton-api-ruby/pull/60/files

**Comment by slate17** [comment]
Yeah, it is failing. I am getting 404 Response. If I remove the extra slash it works.

**Comment by amg-web** [comment]
v3.0.2 - can not start meeting with scalelite, 
I think same reason

How can I enable debug logging?

**Comment by slate17** [comment]
Updated to 3.0.2, still the same.

#5070 is the same Problem.
